### PR TITLE
Tohirjon refactor

### PR DESCRIPTION
**Pull request by TohirjonIbnAlisher**

### CODE REVIEW

**Review by Boburm1rzo — APPROVED** [review]

**Review by BegzhanMaxamatxanov — APPROVED** [review]

**Review by Akhmadovich03 — APPROVED** [review]

**Comment by Abdulazim1771** [comment]
G

**Comment by Abdulazim1771** [comment]
Good

**Comment by Abdulazim1771** [comment]
Lgtm

**Comment by Abdulazim1771** [comment]
Lgtm

**Comment by Abdulazim1771** [comment]
Hdhdh

**Review by Abdulazim1771 — APPROVED** [review]

**Pull request merged**
